{% set name = "nested-lookup" %}
{% set version = "0.2.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6fa832748c90381f2291d850809e32492519ee5f253d6a5acbc29d937eca02e8

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - six

test:
  requires:
    - python {{ python_min }}
  imports:
    - nested_lookup

about:
  home: https://github.com/russellballestrini/nested-lookup
  # NOTE : The author of nested-lookup releases the code to the public domain,
  # so the source is licensed as MIT for the purposes of use in Conda Forge.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python functions for working with deeply nested documents (lists and dicts)
  dev_url: https://git.unturf.com/python/nested-lookup/

extra:
  recipe-maintainers:
    - moorepants
